const path = require('path')
const readFile = require('read-file-utf8')
const writeFile = require('write-file-utf8')

const graphqlDir = path.join(__dirname, '..', 'graphql')

async function generateSchemaJs () {
  try {
    const schemaGraphqlFilepath = path.join(graphqlDir, 'schema.graphql')
    const schemaJsFilepath = path.join(graphqlDir, 'schema.js')

    const schemaSource = await readFile(schemaGraphqlFilepath)

    const moduleContent = [
      '// DO NOT EDIT THIS FILE',
      '//',
      '// it is generated by command',
      '//',
      '//     npm run generate:src/graphql/schema.js',
      '//',
      'module.exports = {',
      '  graphqlCcxtSchemaSource: `',
      schemaSource + '`',
      '}'
    ].join('\n')

    await writeFile(schemaJsFilepath, moduleContent)
  } catch (error) {
    console.error(error)

    throw error
  }
}

generateSchemaJs()
